### ISSUE TITLE
Name FPItem causes conflict

### ISSUE THREAD

**Issue by mattneub** [kballard/feedparser#21]
The class name FPItem causes a conflict because of the FileProvider framework:

> Class FPItem is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/FileProvider.framework/FileProvider (0x11a7d0e08) and /Users/mattneuburg/Library/Developer/CoreSimulator/Devices/47520677-FD7B-46BA-8CC9-401961EC9C08/data/Containers/Bundle/Application/3322D6B6-3E91-4B2A-9D32-AFE58210D35A/TidBITSRSS10.app/TidBITSRSS10 (0x108c62ad0). One of the two will be used. Which one is undefined.

It was always wrong to use a name of the form capital letter capital letter camel-case word, as that is reserved for Apple. I suggest using a different prefix throughout, such as "FPP" (the extra P is meaningless).

[It is easy to make this change manually and I have done so in my copy, so no rush on this.]

**Comment by kballard** [comment]
Hmm, rather annoying that they've decided to use the `FP` prefix internally even though `FP` isn't a public prefix for Apple frameworks (the FileProvider framework appears to use `NSFileProvider` as the prefix for public classes).

**Comment by mattneub** [comment]
Yes, and it's not clear that the conflict is really troublesome, but "which one is undefined" is a scary phrase and I thought it advisable to silence the warning. As I said, this was trivially easy. Nothing to get our knickers in a twist about.

**Comment by kballard** [comment]
The conflict is definitely a problem. If the FileProvider.framework version "wins", then FeedParser is horribly broken, and if the FeedParser one wins, then FileProvider.framework is presumably broken.

**Comment by kballard** [comment]
Fixed in 7d7ebd8fd452fdde8734ea1ea0aed91e254559e3.

I went with the prefix `FDP` instead, both because `FPP` doesn't actually map to anything (there's only one "P" in "FeedParser") and because `FPPParser` just looks silly.

I also provided `@compatibility_alias`es for all public classes, and deprecated aliases for all of the enums / constants. The only thing there's no alias for is a protocol, but it's just an internal implementation detail so it doesn't matter. This means any existing code using e.g. `FPItem` will continue to work, although it's probably a good idea to switch to the `FDP` prefix anyway.

**Comment by mattneub** [comment]
Not that it really matters, but there's a tiny bug in commit 7d7ebd8 - in its compatibility alias line, FPEXtensionNode is misspelled (capital X).

**Comment by lilyball** [comment]
Oops. I'll fix it, thanks for pointing it out.

**Comment by lilyball** [comment]
Fixed in 524a3629db86ac45335adca32ffad3004c316c08.
